[package]
name = "mkshell"
version = "0.1.0"
authors = ["julio @ear7h"]
edition = "2018"


[dependencies]
termion = "1.5.6"
unicode-width = "0.1.8"
mio = { version = "0.7.7", features = ["os-poll", "os-ext"] }
aho-corasick = { path = "vendor/aho-corasick" }
nix = "0.19.1"
clap = "2.33.3"
